image: ddgg/oop_2020:build_v1

pipelines:
  default:
    - step:
        script:
          - pushd 07_qt/02_exercise/
          -   mkdir build-project && pushd build-project
          -     qmake ../project
          -     make -j4
          -     pushd tests/speed
          -       LD_LIBRARY_PATH=../../utils ./speed -o test_detail.xml,xunitxml
          -     popd
          -     pushd tests/acceleration
          -       LD_LIBRARY_PATH=../../utils ./acceleration -o test_detail.xml,xunitxml
          -     popd
          -     pushd tests/displacement
          -       LD_LIBRARY_PATH=../../utils ./displacement -o test_detail.xml,xunitxml
          -     popd
          -   popd
          - popd
          - .ci/collect_reports.sh
