image: ddgg/oop_2020:build_v1

pipelines:
  default:
    - step:
        script:
          - pushd 05_design_patterns/02_exercise/
          -   git clone --depth=1 --branch=release-1.10.0 https://github.com/google/googletest.git
          -   rm -rf googletest/.git
          -   pushd googletest && mkdir build && pushd build
          -       cmake ../ && make -j4
          -   popd && popd
          -   pushd project && mkdir build && pushd build
          -       cmake ../ && make -j4
          -       ./runner
          -       tests/tests --gtest_output=xml
          -   popd && popd
          - popd
          - .ci/collect_reports.sh
